### ISSUE TITLE
Incorrect result with input longer than block size

### ISSUE THREAD

**Issue by maugre** [cxmcc/tiger#1]
I discovered that the result doesn't match the expected values when the input is longer than the block size.

I hacked a test as part of the package I was developing (sorry it doesn't match your code style - it can be modified) that shows this problem.

The result is: "Result effdaebedf2fb2e5bb855e5f29e99c100167fc9f5c638a56 does not match! Expected: cdf0990c5c6b6b0bddd63a75ed20e2d448bf44e15fde0df4"

The other cases are fine. I used the command `printf 'A%0.s' {1..1024} | rhash --tiger -` to generate the expected values.

func TestHashFunc(t *testing.T) {
	tests := []struct {
		data   []byte
		expect string
	}{
		{[]byte(strings.Repeat("A", 64)), "acadbe8f13eafe7d78a288e49524738d8024dd52a759a933"},
		{[]byte(strings.Repeat("A", 65)), "154c1ce7c56330ad3a39805b759f9eb8addee63d58c9fbd3"},
		{[]byte(strings.Repeat("A", 1024)), "cdf0990c5c6b6b0bddd63a75ed20e2d448bf44e15fde0df4"},
	}

	hasher := tiger.New()
	for _, test := range tests {
		hasher.Reset()
		hasher.Write(test.data)
		hashString := hex.EncodeToString(hasher.Sum(nil))

		if hashString != test.expect {
			t.Errorf("Result %s does not match! Expected: %s", hashString, test.expect)
		}
	}
}

**Comment by cxmcc** [comment]
@maugre Thank you for pointing it out. You are absolutely correct. I found the bug, it's fixed here: https://github.com/cxmcc/tiger/commit/833242031fd28ec2ab036edf3019edab87fc97e3
